get_warnings_for_coords_response_data = {
    "type": "Feature",
    "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
            [
                [
                    [625582, 489240],
                    [625279, 489074],
                    [625579, 487841],
                    [624897, 486274],
                    [624333, 485772],
                    [623139, 485933],
                    [623125, 486292],
                    [619402, 487695],
                    [619160, 488503],
                    [619769, 489157],
                    [619153, 489480],
                    [619531, 489968],
                    [622299, 490723],
                    [623465, 491699],
                    [623156, 492065],
                    [623663, 492253],
                    [624274, 491483],
                    [625582, 489240],
                ],
            ],
        ],
    },
    "properties": {
        "location": {
            "type": "Municipal",
            "properties": {
                "gemeindenr": 91901,
                "name": "Wien Döbling",
                "urlname": "wien_doebling",
            },
        },
        "warnings": [
            {
                "type": "Warning",
                "properties": {
                    "warnid": 10,
                    "chgid": 202506260,
                    "verlaufid": 12,
                    "warntypid": 6,
                    "begin": "26.06.2025 00:00",
                    "end": "26.06.2025 23:59",
                    "create": "2025-06-26 07:00:00+00",
                    "text": "Es ist mit starker Hitzebelastung zu rechnen.",
                    "auswirkungen": "* Erhöhte Körpertemperatur\n* Erhöhter Puls\n* Schwäche/Müdigkeit\n* Kopfschmerzen\n* Muskelkrämpfe\n* Trockener Mund und Hals\n* Verwirrtheit, Schwindel, Bewusstseinsstörungen\n* Übelkeit, Erbrechen, Durchfall",
                    "empfehlungen": "* Meiden Sie direktes Sonnenlicht! Achten Sie darauf, dass Kinder vor der Sonne geschützt sind!\n* Meiden Sie verbaute und versiegelte Plätze wo es keinen Schatten gibt.\n* Gehen Sie nicht in der heißesten Tageszeit nach draußen!\n* Ziehen Sie die Vorhänge zu bzw. schließen Sie die Jalousien. Öffnen Sie die Fenster vorwiegend in der Nacht bzw. in den kühlen Morgenstunden!\n* Vermeiden Sie große Anstrengungen bzw. verschieben Sie körperliche Aktivitäten im Freien auf die frühen Morgenstunden oder den Abend!\n* Tragen Sie luftige, helle Kleidung und eine Kopfbedeckung!\n* Nehmen Sie eine kühle Dusche! Auch kalte Arm- und Fußbäder wirken entlastend.\n* Trinken Sie ausreichend und regelmäßig (mindestens 2 - 3 Liter pro Tag)! Optimal sind Wasser, ungesüßter Tee oder mit Wasser verdünnte Fruchtsäfte.\n* Denken Sie an ältere Mitmenschen und Kinder, dass auch diese regelmäßig trinken. \n* Bevorzugen Sie leichtes Essen!\n* Meiden Sie Alkohol!",
                    "meteotext": None,
                    "updategrund": None,
                    "warnstufeid": 2,
                    "rawinfo": {
                        "wtype": 6,
                        "wlevel": 2,
                        "start": "1750888800",
                        "end": "1750975140",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 4642,
                    "chgid": 1,
                    "verlaufid": 1,
                    "warntypid": 5,
                    "begin": "26.06.2025 12:00",
                    "end": "27.06.2025 00:00",
                    "create": "2025-06-26 09:02:00+00",
                    "text": "Orange Gewitterwarnung von Do, 26.06.2025 12:00 bis Fr, 27.06.2025 00:00",
                    "auswirkungen": "*  Blitzschlag kann Gebäude oder Bäume in Brand stecken.\r\n*  Aufgrund von Sturmböen können Gegenstände herumgewirbelt werden, große Äste abbrechen und Bäume entwurzelt werden.\r\n*  Umgestürzte Bäume oder Blitzschläge können Stromausfälle verursachen.\r\n*  Dachziegel können herunterfallen oder Vordächer beschädigt werden.\r\n*  Im Straßen-, Schienen- und Flugverkehr ist mit Behinderungen zu rechnen.\r\n*  Stark erhöhte Unfallgefahr im Straßenverkehr durch Seitenwind, Aquaplaning und schlechte Sicht\r\n*  Straßen können aufgrund von Muren, umgestürzten Bäumen oder Unterspülungen unpassierbar sein.\r\n*  Unterführungen können überflutet sein.\r\n*  Bäche können über die Ufer treten oder Keller und Garagen überflutet werden.\r\n*  Hagelschlag kann Obstkulturen, Glashäuser oder Fahrzeuge beschädigen.",
                    "empfehlungen": "*  Beobachten Sie die lokale Wetterentwicklung und beachten Sie die Blitzgefahr, rechnen Sie mit raschen Entwicklungen und Änderungen der Gewitterzugbahn!\r\n*  Sichern Sie rechtzeitig bewegliche Gegenstände im Freien (wie z. B. Partyzelte, Trampoline oder Gartenmöbel)! Spannen Sie Sonnenschirme ab und ziehen Sie Markisen ein!\r\n*  Planen Sie Verspätungen im Straßen-, Schienen- und Flugverkehr ein!\r\n*  Schließen Sie Fenster, Türen und Garagentore sowie Dachfenster und Lichtkuppeln!\r\n*  Rechnen Sie mit vorübergehenden Stromausfällen!\r\n*  Suchen Sie im Freien rechtzeitig Schutz!\r\n*  Beachten Sie Gewitter- und Sturmwarnungen an Seen!\r\n*  Landen Sie Sportfluggeräte frühzeitig, laufen Sie mit Booten zügig Häfen an!\r\n*  Stellen Sie Kranarbeiten bei drohender Gefahr frühzeitig ein!\r\n*  Beachten Sie die Anweisungen der zuständigen Behörden!",
                    "meteotext": "Im Vorfeld einer Kaltfront ist von Westen her in der labilen Luftmasse recht verbreitet mit teils kräftigen Gewittern zu rechnen. Dabei besteht die Gefahr von schweren bis orkanartigen Sturmböen, Starkregen und lokal auch von Hagel.",
                    "updategrund": "",
                    "warnstufeid": 2,
                    "rawinfo": {
                        "wtype": 5,
                        "wlevel": 2,
                        "start": "1750932000",
                        "end": "1750975200",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 4643,
                    "chgid": 0,
                    "verlaufid": 2,
                    "warntypid": 1,
                    "begin": "26.06.2025 16:00",
                    "end": "27.06.2025 00:00",
                    "create": "2025-06-26 07:26:00+00",
                    "text": "Orange Windwarnung von Do, 26.06.2025 16:00 bis Fr, 27.06.2025 00:00",
                    "auswirkungen": "*  Große Äste können abbrechen, vereinzelt können auch Bäume entwurzelt werden.\r\n*  Umgestürzte Bäume können Stromausfälle verursachen.\r\n*  Im Straßen-, Schienen- und Flugverkehr ist mit Verzögerungen zu rechnen.\r\n*  Stark erhöhte Unfallgefahr durch Seitenwind im Straßenverkehr, insbesondere auf Brücken und exponierten Straßenzügen\r\n*  Dachziegel können herunterfallen oder Vordächer beschädigt werden.\r\n*  Kranarbeiten sind nicht oder nur sehr eingeschränkt möglich.",
                    "empfehlungen": "*  Meiden Sie Wälder, Parks und Alleen!\r\n*  Reduzieren Sie im Straßenverkehr die Geschwindigkeit, vermeiden Sie Überholmanöver und halten Sie Abstand!\r\n*  Planen Sie Verspätungen im Straßen-, Schienen- und Flugverkehr ein!\r\n*  Parken Sie Fahrzeuge nicht in der Nähe von Bäumen!\r\n*  Schränken Sie Outdooraktivitäten ein!\r\n*  Rechnen Sie mit lokalen Ausfällen der Energieversorgung!\r\n*  Beachten Sie die Anweisungen der zuständigen Behörden!\r\n*  Sichern Sie rechtzeitig bewegliche Gegenstände im Freien (z. B. Partyzelte, Trampoline oder Gartenmöbel), Kinderwagen können leicht umstürzen!\r\n*  Rechnen Sie auf den Bergen mit noch erheblich höheren Sturmspitzen!\r\n*  Beachten Sie Sturmwarnungen an Seen!",
                    "meteotext": "Mit Durchzug kräftiger Gewitter lebt der Wind ab dem Nachmittag bis in die Nacht hinein zeitweise stürmisch auf. Dabei werden verbreitet Windspitzen um 90km/h erwartet, örtlich auch mehr.",
                    "updategrund": "",
                    "warnstufeid": 2,
                    "rawinfo": {
                        "wtype": 1,
                        "wlevel": 2,
                        "start": "1750946400",
                        "end": "1750975200",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 5,
                    "chgid": 0,
                    "verlaufid": 0,
                    "warntypid": 5,
                    "begin": "26.06.2025 19:00",
                    "end": "26.06.2025 20:00",
                    "create": "2025-06-26 17:25:37.443169+00",
                    "text": "Es ist mit Gewittern zu rechnen.",
                    "auswirkungen": None,
                    "empfehlungen": None,
                    "meteotext": None,
                    "updategrund": None,
                    "warnstufeid": 1,
                    "rawinfo": {
                        "wtype": 5,
                        "wlevel": 1,
                        "start": "1750957200",
                        "end": "1750960800",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 10,
                    "chgid": 202506260,
                    "verlaufid": 21,
                    "warntypid": 6,
                    "begin": "27.06.2025 00:00",
                    "end": "27.06.2025 23:59",
                    "create": "2025-06-26 07:00:00+00",
                    "text": "Es ist mit erhöhter Hitzebelastung zu rechnen.",
                    "auswirkungen": "* Erhöhte Körpertemperatur\n* Erhöhter Puls\n* Schwäche/Müdigkeit\n* Kopfschmerzen\n* Muskelkrämpfe\n* Trockener Mund und Hals\n* Verwirrtheit, Schwindel, Bewusstseinsstörungen\n* Übelkeit, Erbrechen, Durchfall",
                    "empfehlungen": "* Meiden Sie direktes Sonnenlicht! Achten Sie darauf, dass Kinder vor der Sonne geschützt sind!\n* Meiden Sie verbaute und versiegelte Plätze wo es keinen Schatten gibt.\n* Gehen Sie nicht in der heißesten Tageszeit nach draußen!\n* Ziehen Sie die Vorhänge zu bzw. schließen Sie die Jalousien. Öffnen Sie die Fenster vorwiegend in der Nacht bzw. in den kühlen Morgenstunden!\n* Vermeiden Sie große Anstrengungen bzw. verschieben Sie körperliche Aktivitäten im Freien auf die frühen Morgenstunden oder den Abend!\n* Tragen Sie luftige, helle Kleidung und eine Kopfbedeckung!\n* Nehmen Sie eine kühle Dusche! Auch kalte Arm- und Fußbäder wirken entlastend.\n* Trinken Sie ausreichend und regelmäßig (mindestens 2 - 3 Liter pro Tag)! Optimal sind Wasser, ungesüßter Tee oder mit Wasser verdünnte Fruchtsäfte.\n* Denken Sie an ältere Mitmenschen und Kinder, dass auch diese regelmäßig trinken. \n* Bevorzugen Sie leichtes Essen!\n* Meiden Sie Alkohol!",
                    "meteotext": None,
                    "updategrund": None,
                    "warnstufeid": 1,
                    "rawinfo": {
                        "wtype": 6,
                        "wlevel": 1,
                        "start": "1750975200",
                        "end": "1751061540",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 10,
                    "chgid": 202506260,
                    "verlaufid": 41,
                    "warntypid": 6,
                    "begin": "29.06.2025 00:00",
                    "end": "29.06.2025 23:59",
                    "create": "2025-06-26 07:00:00+00",
                    "text": "Es ist mit erhöhter Hitzebelastung zu rechnen.",
                    "auswirkungen": "* Erhöhte Körpertemperatur\n* Erhöhter Puls\n* Schwäche/Müdigkeit\n* Kopfschmerzen\n* Muskelkrämpfe\n* Trockener Mund und Hals\n* Verwirrtheit, Schwindel, Bewusstseinsstörungen\n* Übelkeit, Erbrechen, Durchfall",
                    "empfehlungen": "* Meiden Sie direktes Sonnenlicht! Achten Sie darauf, dass Kinder vor der Sonne geschützt sind!\n* Meiden Sie verbaute und versiegelte Plätze wo es keinen Schatten gibt.\n* Gehen Sie nicht in der heißesten Tageszeit nach draußen!\n* Ziehen Sie die Vorhänge zu bzw. schließen Sie die Jalousien. Öffnen Sie die Fenster vorwiegend in der Nacht bzw. in den kühlen Morgenstunden!\n* Vermeiden Sie große Anstrengungen bzw. verschieben Sie körperliche Aktivitäten im Freien auf die frühen Morgenstunden oder den Abend!\n* Tragen Sie luftige, helle Kleidung und eine Kopfbedeckung!\n* Nehmen Sie eine kühle Dusche! Auch kalte Arm- und Fußbäder wirken entlastend.\n* Trinken Sie ausreichend und regelmäßig (mindestens 2 - 3 Liter pro Tag)! Optimal sind Wasser, ungesüßter Tee oder mit Wasser verdünnte Fruchtsäfte.\n* Denken Sie an ältere Mitmenschen und Kinder, dass auch diese regelmäßig trinken. \n* Bevorzugen Sie leichtes Essen!\n* Meiden Sie Alkohol!",
                    "meteotext": None,
                    "updategrund": None,
                    "warnstufeid": 1,
                    "rawinfo": {
                        "wtype": 6,
                        "wlevel": 1,
                        "start": "1751148000",
                        "end": "1751234340",
                    },
                },
            },
            {
                "type": "Warning",
                "properties": {
                    "warnid": 10,
                    "chgid": 202506260,
                    "verlaufid": 51,
                    "warntypid": 6,
                    "begin": "30.06.2025 00:00",
                    "end": "30.06.2025 23:59",
                    "create": "2025-06-26 07:00:00+00",
                    "text": "Es ist mit erhöhter Hitzebelastung zu rechnen.",
                    "auswirkungen": "* Erhöhte Körpertemperatur\n* Erhöhter Puls\n* Schwäche/Müdigkeit\n* Kopfschmerzen\n* Muskelkrämpfe\n* Trockener Mund und Hals\n* Verwirrtheit, Schwindel, Bewusstseinsstörungen\n* Übelkeit, Erbrechen, Durchfall",
                    "empfehlungen": "* Meiden Sie direktes Sonnenlicht! Achten Sie darauf, dass Kinder vor der Sonne geschützt sind!\n* Meiden Sie verbaute und versiegelte Plätze wo es keinen Schatten gibt.\n* Gehen Sie nicht in der heißesten Tageszeit nach draußen!\n* Ziehen Sie die Vorhänge zu bzw. schließen Sie die Jalousien. Öffnen Sie die Fenster vorwiegend in der Nacht bzw. in den kühlen Morgenstunden!\n* Vermeiden Sie große Anstrengungen bzw. verschieben Sie körperliche Aktivitäten im Freien auf die frühen Morgenstunden oder den Abend!\n* Tragen Sie luftige, helle Kleidung und eine Kopfbedeckung!\n* Nehmen Sie eine kühle Dusche! Auch kalte Arm- und Fußbäder wirken entlastend.\n* Trinken Sie ausreichend und regelmäßig (mindestens 2 - 3 Liter pro Tag)! Optimal sind Wasser, ungesüßter Tee oder mit Wasser verdünnte Fruchtsäfte.\n* Denken Sie an ältere Mitmenschen und Kinder, dass auch diese regelmäßig trinken. \n* Bevorzugen Sie leichtes Essen!\n* Meiden Sie Alkohol!",
                    "meteotext": None,
                    "updategrund": None,
                    "warnstufeid": 1,
                    "rawinfo": {
                        "wtype": 6,
                        "wlevel": 1,
                        "start": "1751234400",
                        "end": "1751320740",
                    },
                },
            },
        ],
    },
}
